main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    # path('', views.home, name="home"),
    path('', views.add, name="add"),
    path('add/items', views.add_items, name="add_items"),
    path('delete/items/<int:todo_id>', views.delete_items, name="delete_items"),

]

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models


class Todo(models.Model):
    added_date = models.DateTimeField()
    text = models.CharField(max_length=250)

main/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.http import HttpResponseRedirect
from .models import Todo
from django.urls import reverse


def home(request):
    return render(request, 'base.html')


def add(request):
    todo_items = Todo.objects.all().order_by('added_date')
    return render(request, 'main/index.html', {"todo_items": todo_items})


@csrf_exempt
def add_items(request):
    # print(request.POST)
    date = timezone.now()
    content = request.POST["content"]
    Todo.objects.create(added_date=date, text=content)
    return HttpResponseRedirect(reverse('main:add'))


@csrf_exempt
def delete_items(request, todo_id):
    Todo.objects.get(id=todo_id).delete()
    return HttpResponseRedirect(reverse('main:add'))

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">ToDo</a>
</nav>
<div class="container">
{% block content%}

    {% endblock %}
</div>
</body>
</html>

templates/main/index.html
{% extends 'base.html' %}

{% block content %}

<div class="row mt-4">
    <div class = "col">
        <h2>Add Items</h2>
        <form action="{% url 'main:add_items' %}" method = "post"  >
        <input type="text" class="form-control mb-3 mt-3 mr-sm-2" id="inlineFormInput" name = "content" placeholder="Add to your todo list">
        <button type="submit" class="btn btn-primary mb-2">Submit</button>
        </form>
    </div>
</div>


    <div class = "row mt-4">
        <div class = "col">
            <ul class="list-group">
              {% for todo in todo_items %}
                <li class="list-group-item">{{todo.text}}
                 <div class="float-right">
                     <form action="{%url 'main:delete_items' todo.id%}" method="post">
                    <button type="submit" class="btn btn-danger">Delete</button>
                     </form>
                </div>
                </li>

              {% endfor %}
            </ul>
        </div>
    </div>



{% endblock %}